- name: Install OS Packages
  apt:
    name: '{{ item }}'
  with_items: '{{ os_packages }}'
- name: install atom editor
  apt:
    deb: https://github.com/atom/atom/releases/download/v{{ version }}/atom-amd64.deb
    state: installed
