- name: Install OS Packages
  yum:
    name: '{{ os_packages }}'
    update_cache: yes
- name: install atom editor
  yum:
    name: https://github.com/atom/atom/releases/download/v{{ version }}/atom.x86_64.rpm
    state: installed

# FIXME:
# following does not work:
# Error message: Could not find config.cson. Run Atom first?
# - block:
#   - name: get enabled atom packages
#     command: apm list -i -e -b -p
#     changed_when: False
#     become_user: '{{ installation_os_user }}'
#     register: apm_enabled
#   - name: disable atom welcome package
#     command: 'apm disable welcome'
#     when: apm_enabled.stdout.find("welcome") != -1
#   become_user: '{{ in
