- name: Install OS Packages
  yum:
    name: '{{ os_packages }}'
    update_cache: yes
- name: install atom editor
  yum:
    name: https://github.com/atom/atom/releases/download/v{{ version }}/atom.x86_64.rpm
    state: installed
